version: '3'
services:
  stanbroke_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "<YourStrong!Passw0rd>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - 'mssql:/var/opt/mssql_stanbroke'
volumes:
  mssql:
    external: true
